services:
    nginx:
        container_name: nginx
        build:
            context: ./
            dockerfile: ./docker/nginx/Dockerfile
        restart: unless-stopped
        ports:
            - "${NGINX_PORT:-80}:80"
        volumes:
            - ./backend:/var/www
        links:
            - php

    mysql:
        container_name: mysql
        image: mysql:8.0
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=user
            - MYSQL_PASSWORD=user
            - MYSQL_DATABASE=app
        restart: unless-stopped
        volumes:
            - mysql_data:/var/lib/mysql  # Специальный volume для данных
        ports:
            - "${MYSQL_PORT:-3306}:3306"

#    llm:
#        container_name: llm
#        env_file:
#            - path: .env
#              required: true
#        build:
#          context: ./
#          dockerfile: ./docker/llm/Dockerfile
#          args:
#            - LLM_URL=${LLM_URL:-false} # Doesn't download LLM by default
#        restart: unless-stopped
#        links:
#            - mysql

    php:
        container_name: php
        build:
            context: ./
            dockerfile: ./docker/php/Dockerfile
            args:
                WWWUSER: ${USER}
        restart: unless-stopped
        user: ${USER}
        volumes:
            - ./backend:/var/www/
        links:
            - mysql
#            - llm

    node:
        container_name: node
        build:
            context: ./
            dockerfile: ./docker/node/Dockerfile
        ports:
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        restart: unless-stopped
        tty: true
        volumes:
            -  ./backend:/var/www

    redis:
        container_name: redis
        image: redis
        restart: unless-stopped
        ports:
            - "${REDIS_PORT:-6379}:6379"

volumes:
    mysql_data:
